project:
  type: website
  output-dir: docs

website:
  title: "Mckenna Cooper"
  favicon: img/logo.png # NOTE: that the `favicon` is a `website` level option (not under `navbar`)
  navbar:
    title: false # override printing your website `title` (e.g. "Mckenna Cooper" on line 6)
    logo: img/logo_transparent.png
    logo-alt: "Mckenna Cooper"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: img/mcooper_resume.pdf
        text: Resume
  page-footer:
    background: light # or `dark`
    left: Copyright 2025, Mckenna Cooper
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/mckenna-cooper/mckenna-cooper.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
