project:
  type: website
  output-dir: docs

website:
  title: "Mckenna Cooper"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: referenced.qmd
        text: Referenced
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
